<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyName>Jellyfin.Plugin.Monochrome</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.Monochrome</RootNamespace>
    <Version>1.1.0.0</Version>
    <Authors>Monochrome Community / Jellyfin</Authors>
    <PackageId>Jellyfin.Plugin.Monochrome</PackageId>
    <Description>Monochrome Music streaming and metadata plugin for Jellyfin 12.0</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.0.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="12.0.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration/configPage.html" />
    <EmbeddedResource Include="Web/searchPage.html" />
  </ItemGroup>

</Project>

